name = "github-ai-intelligence-tail"
main = "src/tail-worker.ts"
compatibility_date = "2024-01-01"

# D1 Database binding (same as main worker)
[[d1_databases]]
binding = "DB"
database_name = "github-intelligence"
database_id = "90ad28ff-c07b-41c3-90bf-44da6f903687"

# R2 Storage binding (same as main worker for backup)
[[r2_buckets]]
binding = "STORAGE"
bucket_name = "github-analyses"

# Environment variables
[vars]
ENVIRONMENT = "production"

# Development settings
[env.development]
vars = { ENVIRONMENT = "development" }
